### ISSUE TITLE
[Feature request] Hide all cursors

### ISSUE THREAD

**Issue by Kristinita** [shagabutdinov/sublime-remove-selection#2]
### 1. Request

It would be nice, if Remove Selection can remove all cursors include last cursors.

### 2. Justification

For example, if in package [**user have output to new view**](http://stackoverflow.com/a/43582267/5951529), not to Sublime Text console, cursor spoils the look of view.

### 3. Steps to reproduce

I open any view in Subime Text → I run Remove Selection commands.

### 4. Actual behavior

Remove Selection remove cursors, but if user has 1 cursor, Remove Selection doesn't hide last cursor.

### 5. Expected behavior

If user has ≥ 1 cursor in view: <kbd>Ctrl+Shift+P</kbd> (<kbd>⌘⇧p</kbd> for Mac) → `Remove Selection: Clear Cursors` → user has no cursors in view.

### 6. Not helped

1. Cursor [**hide for me**](http://stackoverflow.com/a/36448854/5951529), if <kbd>Alt+Left_Click</kbd>, but command doesn't work, if I want run this command into in my Sublime Text plugin like: `view.window().run_command('hide_cursors')`; because the execution of command depends on the position of the mouse, which can be different.

Thanks.

**Comment by Kristinita** [comment]
[**clear() method**](https://www.sublimetext.com/docs/3/api_reference.html#sublime.Selection) solve my problem.

Thanks.

**Comment by shagabutdinov** [comment]
No problem :)))
